packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  esbuild: true
  sharp: true
minimumReleaseAgeExclude:
  - '@lezer/css@1.3.4'
  - '@marijn/find-cluster-break@1.0.3'
  - crelt@1.0.7
  - esrap@2.2.13
